/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.jlokalize.ui;

import java.awt.Font;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import org.jlokalize.Main;
import org.tools.common.CentralStatic;
import org.tools.i18n.PropertyWithStats;
import org.tools.io.Resource;
import org.tools.io.ResourceUtils;
import org.tools.ui.JHyperlinkLabel;

/**
 * About dialog showing some links, the version and the license.
 *
 * @author Trilarion 2010-2011
 */
public class AboutDlg extends JDialog {

    private static final long serialVersionUID = 1L;
    private static final Logger LOG = Logger.getLogger(AboutDlg.class.getName());

    /**
     * Creates new form AboutDlg. Populates the dialog with data.
     *
     * @param parent The parent frame.
     * @param modal If modal or not.
     */
    public AboutDlg(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        PropertyWithStats lang = CentralStatic.retrieve("lang-prop");
        setTitle(lang.get("about.title"));
        String version = MessageFormat.format(lang.get("about.message"), Main.options.get("program.version"));
        versionInfo.setText(version);

        websiteLink.setText(lang.get("about.website"));
        websiteLink.setLink(Main.options.get("website"));
        documentationLink.setText(lang.get("about.documentation"));
        documentationLink.setLink(Main.options.get("website.help"));
        okButton.setText(lang.get("dialog.ok"));

        licenseLabel.setText(lang.get("about.license"));

        // take the license from inside the jar file
        String license = null;
        try {
            Resource licenseFile = ResourceUtils.asResource(Main.jarPath + "JLokalize.jar/license.txt");
            license = ResourceUtils.readText(licenseFile);
        } catch (IOException ex) {
            LOG.log(Level.SEVERE, null, ex);
        }
        licenseInfo.setText(license);
        licenseInfo.setCaretPosition(0);
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        licencseScroller = new JScrollPane();
        licenseInfo = new JTextArea();
        okButton = new JButton();
        logoImage = new JLabel();
        versionInfo = new JLabel();
        licenseLabel = new JLabel();
        websiteLink = new JHyperlinkLabel();
        documentationLink = new JHyperlinkLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setLocationByPlatform(true);
        setModal(true);
        setName("aboutDlg"); // NOI18N
        setResizable(false);

        licenseInfo.setEditable(false);
        licenseInfo.setColumns(40);
        licenseInfo.setFont(new Font("Monospaced", 0, 11)); // NOI18N
        licenseInfo.setLineWrap(true);
        licenseInfo.setRows(10);
        licenseInfo.setToolTipText("License information");
        licenseInfo.setWrapStyleWord(true);
        licencseScroller.setViewportView(licenseInfo);

        okButton.setText("Ok");
        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        logoImage.setIcon(new ImageIcon(getClass().getResource("/icons/jlokalize.png"))); // NOI18N

        versionInfo.setText("Versioninfo");

        licenseLabel.setText("License info");

        websiteLink.setText("Website");

        documentationLink.setText("Documentation");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoImage)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(licencseScroller, GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(licenseLabel)
                    .addComponent(okButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addComponent(versionInfo, GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(websiteLink, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(documentationLink, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(logoImage, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(versionInfo, GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                            .addComponent(websiteLink, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(documentationLink, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(licenseLabel, GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)))
                .addGap(4, 4, 4)
                .addComponent(licencseScroller, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 'Ok' button has been pressed, dispose the dialog.
     *
     * @param evt
     */
    private void okButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * Entry point for showing the modal about dialog.
     *
     * @param parent
     */
    public static void start(JFrame parent) {
        AboutDlg dialog = new AboutDlg(parent, true);
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JHyperlinkLabel documentationLink;
    private JScrollPane licencseScroller;
    private JTextArea licenseInfo;
    private JLabel licenseLabel;
    private JLabel logoImage;
    private JButton okButton;
    private JLabel versionInfo;
    private JHyperlinkLabel websiteLink;
    // End of variables declaration//GEN-END:variables

}
