/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.jlokalize.ui;

import java.awt.Component;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import org.tools.common.CentralStatic;
import org.tools.common.Named;
import org.tools.common.Utils;
import org.tools.i18n.PropertyWithStats;

/**
 * Create a new language dialog. Very simple, either you select the three codes
 * corresponding to language, country, variant by yourself or you can choose the
 * standard notation from a list which is taken from the internal Java Locales
 * list.
 * 
 * @author Trilarion 2010-2011
 */
public class NewLanguageDlg extends JDialog {

    private static final long serialVersionUID = 1L;

    /** We need to know if the dialog was canceled or not. */
    private boolean wasCanceled = true;
    /** A locales list, used for display in the drop down box */
    private List<Named<Locale>> locales;

    /** Creates new form NewLanguageDlg, fill drop down box with Locales names
     * @param parent
     */
    public NewLanguageDlg(Frame parent) {
        super(parent, true);
        initComponents();
        
        // i18n of the dialog
        PropertyWithStats lang = CentralStatic.retrieve("lang-prop");
        okButton.setText(lang.get("dialog.ok"));
        cancelButton.setText(lang.get("dialog.cancel"));
        languageListLabel.setText(lang.get("newlanguage.label.list"));
        languageLabel.setText(lang.get("newlanguage.label.language"));
        countryLabel.setText(lang.get("newlanguage.label.country"));
        variantLabel.setText(lang.get("newlanguage.label.variant"));
        setTitle(lang.get("newlanguage.title"));

        // more initialization
        locales = new ArrayList<Named<Locale>>(300);
        Locale[] locs = Locale.getAvailableLocales();
        for (int ki = 0; ki < locs.length; ki++) {
            Named<Locale> locale = new Named<Locale>(Utils.capitalize(locs[ki].getDisplayName()), locs[ki]);
            locales.add(locale);
        }
        // sort for names alphabetically
        Collections.sort(locales, Named.comparator); 
        DefaultComboBoxModel model = new DefaultComboBoxModel(locales.toArray());
        languageComboBox.setModel(model);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        languageLabel = new JLabel();
        languageComboBox = new JComboBox();
        countryLabel = new JLabel();
        variantLabel = new JLabel();
        variantTextField = new JTextField();
        okButton = new JButton();
        cancelButton = new JButton();
        languageTextField = new JTextField();
        countryTextField = new JTextField();
        languageListLabel = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add a language");
        setLocationByPlatform(true);
        setModalityType(ModalityType.APPLICATION_MODAL);
        setName("newLangDlg"); // NOI18N
        setResizable(false);

        languageLabel.setText("Language");

        languageComboBox.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                languageComboBoxItemStateChanged(evt);
            }
        });

        countryLabel.setText("Country");

        variantLabel.setText("Variant");

        okButton.setText("OK");
        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        languageListLabel.setText("Set from list of available idioms");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(languageListLabel)
                    .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                            .addComponent(languageComboBox, Alignment.LEADING, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                    .addComponent(languageTextField, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(languageLabel, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(countryLabel, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(ComponentPlacement.RELATED)
                                        .addComponent(variantLabel, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(countryTextField, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(ComponentPlacement.RELATED)
                                        .addComponent(variantTextField, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)))))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                            .addComponent(cancelButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(okButton, GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {countryTextField, languageTextField, variantTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(languageListLabel)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(languageComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                            .addComponent(languageLabel)
                            .addComponent(countryLabel)
                            .addComponent(variantLabel)))
                    .addComponent(okButton))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(languageTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(variantTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 'Ok' button was pressed, dispose and set canceled to false.
     * @param evt The event.
     */
    private void okButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        wasCanceled = false;
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * 'Cancel' button pressed, just dispose.
     * @param evt The event.
     */
    private void cancelButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * The selection of the drop down box changed, update the code text fields.
     * @param evt 
     */
    private void languageComboBoxItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_languageComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // something has been selected
            int item = languageComboBox.getSelectedIndex();
            Locale locale = locales.get(item).getObject();
            // set fields
            languageTextField.setText(locale.getLanguage());
            countryTextField.setText(locale.getCountry());
            variantTextField.setText(locale.getVariant());
        }
    }//GEN-LAST:event_languageComboBoxItemStateChanged

    /**
     * Sets the dialog visible, waits (because it is modal) for the results and
     * read them out or ignore them if Cancel button was pressed or dialog was
     * closed otherwise (alt+f4, ...).
     * 
     * @return An array of 3 codes (language, country, variant) or null if canceled.
     */
    public String[] execute() {
        setVisible(true);

        String[] ret = null;
        if (!wasCanceled) {
            ret = new String[3];
            ret[0] = languageTextField.getText();
            if (ret[0].isEmpty()) {
                ret[0] = null;
            }
            ret[1] = countryTextField.getText();
            if (ret[1].isEmpty()) {
                ret[1] = null;
            }
            ret[2] = variantTextField.getText();
            if (ret[2].isEmpty()) {
                ret[2] = null;
            }
        }
        return ret;        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton cancelButton;
    private JLabel countryLabel;
    private JTextField countryTextField;
    private JComboBox languageComboBox;
    private JLabel languageLabel;
    private JLabel languageListLabel;
    private JTextField languageTextField;
    private JButton okButton;
    private JLabel variantLabel;
    private JTextField variantTextField;
    // End of variables declaration//GEN-END:variables

}
